# Generated by Django 5.1.2 on 2024-12-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtwapa_branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
