# Generated by Django 5.1.2 on 2024-12-25 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtwapa_branch', '0003_activity_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('KEMRI', 'KEMRI'), ('Health Staff', 'Health Staff')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_updates/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
