# Generated by Django 5.1.2 on 2024-12-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtwapa_branch', '0004_newsupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsUpdate',
        ),
    ]
