# Generated by Django 5.1.2 on 2024-12-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtwapa_branch', '0006_newsupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
