# Generated by Django 5.1.2 on 2024-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtwapa_branch', '0007_patient_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
