# Generated by Django 5.1.2 on 2024-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtwapa_branch', '0008_alter_patient_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('test_count', models.IntegerField(default=0)),
            ],
        ),
    ]
