# Generated by Django 5.1.2 on 2024-12-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtwapa_branch', '0013_tbpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mtb_a_status',
            field=models.CharField(blank=True, choices=[('Detected', 'Detected'), ('Not Detected', 'Not Detected')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='oft_status',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_status',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='randomization_status',
            field=models.CharField(blank=True, choices=[('Randomized', 'Randomized'), ('Unrandomized', 'Unrandomized')], max_length=15, null=True),
        ),
    ]
