# Generated by Django 5.1.2 on 2024-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtwapa_branch', '0015_question_questionchoice_questionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbpatient',
            name='alternative_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='exclusion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='mtb_a_status',
            field=models.CharField(blank=True, choices=[('Detected', 'Detected'), ('Not Detected', 'Not Detected')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='next_evaluation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='oft_status',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='pregnancy_status',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='randomization_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='randomization_status',
            field=models.CharField(choices=[('Randomized', 'Randomized'), ('Not Randomized', 'Not Randomized')], default='Not Randomized', max_length=20),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='referral_facility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbpatient',
            name='study_group',
            field=models.CharField(choices=[('Control', 'Control Group'), ('Treatment', 'Treatment Group'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=20),
        ),
    ]
