# Generated by Django 5.1.2 on 2024-12-29 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtwapa_branch', '0017_tbpatient_date_added_tbpatient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostToFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_follow_up_date', models.DateField(help_text='Date of the last follow-up visit')),
                ('weeks_missing', models.PositiveIntegerField(help_text='Number of weeks since the last visit')),
                ('reason_for_lost_follow_up', models.TextField(blank=True, help_text='Reason why the patient stopped attending', null=True)),
                ('reported_by', models.CharField(help_text='Name of the person reporting the case', max_length=255)),
                ('kemri_project_code', models.CharField(default='KEMRI-TB', help_text='Project code for KEMRI reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_to_follow_ups', to='mtwapa_branch.tbpatient')),
            ],
            options={
                'verbose_name': 'Lost to Follow-Up',
                'verbose_name_plural': 'Lost to Follow-Ups',
                'ordering': ['-last_follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='SeriousAdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Death', 'Death'), ('Severe Reaction', 'Severe Reaction'), ('Other', 'Other')], help_text='Type of serious adverse event', max_length=100)),
                ('event_date', models.DateField(help_text='Date when the event occurred')),
                ('cause_of_death_or_reaction', models.CharField(blank=True, help_text='Cause of the event (if applicable)', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional description or details about the event', null=True)),
                ('reported_by', models.CharField(help_text='Name of the person who reported the event', max_length=255)),
                ('kemri_project_code', models.CharField(default='KEMRI-TB', help_text='Project code for KEMRI reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serious_adverse_events', to='mtwapa_branch.tbpatient')),
            ],
            options={
                'verbose_name': 'Serious Adverse Event',
                'verbose_name_plural': 'Serious Adverse Events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawnConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_date', models.DateField(help_text='Date when the consent was withdrawn')),
                ('reason_for_withdrawal', models.CharField(choices=[('Pregnancy', 'Pregnancy'), ('Relocation', 'Relocation'), ('Other', 'Other')], help_text='Reason for withdrawal of consent', max_length=255)),
                ('additional_details', models.TextField(blank=True, help_text='Any additional details regarding the withdrawal', null=True)),
                ('reported_by', models.CharField(help_text='Name of the person reporting the case', max_length=255)),
                ('kemri_project_code', models.CharField(default='KEMRI-TB', help_text='Project code for KEMRI reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawn_consent_cases', to='mtwapa_branch.tbpatient')),
            ],
            options={
                'verbose_name': 'Withdrawn Consent',
                'verbose_name_plural': 'Withdrawn Consents',
                'ordering': ['-withdrawal_date'],
            },
        ),
    ]
